### ISSUE TITLE
[EndGame] Azure Functions Maven Plugin 1.10.0

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-maven-plugins#1374]
Prepare for releasing Azure Functions Maven Plugin 1.10.0

Tests:

- [x] Support @Retry annotation(andy)
- [x] Telemetry(hanli) 
- [x] Switch to use identity in auth: azure cli, device code, oauth, sp (hanli)
- [x] Support non-java value FUNCTIONS_WORKER_RUNTIME (andy) https://github.com/microsoft/azure-maven-plugins/issues/1209
- [x] Fixes: mvn azure-functions:package fails with NullPointerException  (miller) https://github.com/microsoft/azure-maven-plugins/issues/1212
- [x] Support proxy in auth (hanli) https://github.com/microsoft/azure-maven-plugins/issues/844

Operations:
- [x] Testable Image (hanli)
- [x] Test plan updated (hanli)
- [x] Change log updated (hanli)
- [x] Snapshot version check(andy)
- [x] telemetry tagged(hanli)
- [x] Security Check(andy)
- [x] Check archetype updated(hanli)
- [x] Release to maven central(hanli)
- [x] Tag(hanli)
- [x] Wiki update if necessary(hanli)
- [x] Related issues are closed(hanli)
- [x] Document in docs.microsoft.com are updated with new version (yucwan)
- [x] Update sample at https://github.com/Azure-Samples/azure-functions-samples-java (hanli)
- [x] Milestone complete
- [x] Merge back to develop

**Comment by andxu** [comment]
![image](https://user-images.githubusercontent.com/17075863/112451523-90dad680-8d90-11eb-9457-1c9194803d7e.png)
