### ISSUE TITLE
Add option deploy via zipDeploy on azure-functions plugin

### ISSUE THREAD

**Issue by pragnagopa** [Microsoft/azure-maven-plugins#179]
### Plugin name and version
azure-functions-maven-plugin

Add option to deploy via [ZipDeploy](https://github.com/Azure/app-service-announcements/issues/84)
 to azure-functions-maven-plugin deploy action.
Please see more details [here](https://github.com/Azure/app-service-announcements/issues/110)

**Comment by jdneo** [comment]
`zipDeploy` can also be used in Web App deployment. it will be a replacement for the FTP deployment type.

**Comment by SummerSun** [comment]
### Work items
- [ ] implementation in maven lib module
- [ ] add unit tests
- [ ] add integration tests
- [ ] update readme

**Comment by SummerSun** [comment]
close this one and track our work for both web app and function app in issue #294

**Comment by jdneo** [comment]
@pragnagopa Do we need to stop the Function App when using zip deploy? Seems this is not required according to my observation. Am I right?

**Comment by pragnagopa** [comment]
Can you give me more details on any issue you are running into with the zip deploy?

**Comment by jdneo** [comment]
Sure. About several months ago, when we tried to deploy java function project in the VS Code extension using zipDeploy we find that sometimes the deployment will fail due to the jar file being occupied. So in the implementation, we will stop the function app before deployment and start it after that.

And recently when I'm testing the zip deploy in the Maven plugin, It looks like this issue has been fixed.

I'm confirming that if the stop->start is still required or not for zip deploy to deploy a jar file.
