### ISSUE TITLE
Add deployment type "ZIP" for both web app and function app

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/azure-maven-plugins#294]
### Add deployment type "ZIP" for both web app and function app

SDK team is providing the zip deploy support for function app and web app and it delivers a better performance that FTP deploy, we will add the support in our maven plugin as well.

The implementation will be made in the library module since it will be shared between function app and web app. To do this, we first need to move artifact handler interface to library module and implement both FTP and ZIP handler there.

### Work items
- [x] Extract Artifact handler interface and FTP implementation to the library module
- [x] Implement ZIP artifact handler implementation in the library module
- [x] Add zip deploy for web app
- [x] Add zip deploy for function app
- [x] Update Jar deploy to leverage zip deploy instead of FTP deploy to achieve better performance
- [x] Add unit tests for FTP and ZIP artifact handler in the library module
- [x] Add integration tests for web app ZIP deploy
- [x] Add integration tests for function app ZIP deploy #307 
  - Update zip deploy as default and integration tests will naturally test against zip deploy
- [x] Update README to provide guidance for ZIP deploy for both function app and web app #316
