### ISSUE TITLE
Azure Functions Maven plugin 1.0.0-beta-5 feature plan

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#312]
## Add

- [x] Support zip deploy (https://github.com/Microsoft/azure-maven-plugins/issues/294)
- [x] Support list templates information (https://github.com/Microsoft/azure-maven-plugins/issues/309)

## Change
- [x] Update the template for blob trigger (#326)

**Comment by jdneo** [comment]
@pragnagopa FYI
