### ISSUE TITLE
Maven Plugins Iteration Planning [8/20/2018 - 9/7/2018]

### ISSUE THREAD

**Issue by jdneo** [Microsoft/azure-maven-plugins#349]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Azure Functions plugin
- [x] https://github.com/Microsoft/azure-maven-archetypes/issues/47 Need some validation for parameter values
- [x] https://github.com/Microsoft/azure-maven-archetypes/issues/49 Method name conflicts with the default name of function class
- [ ] 💪 #261 Add more function integration tests
- [ ] 🔵#330 Update EventHub templates to support Cadinality 
#### Adapt to Azure Functions Runtime V2
- [x] https://github.com/Microsoft/azure-maven-archetypes/issues/58 Add FUNCTIONS_WORKER_RUNTIME=java to AppSetting
- [x] https://github.com/Microsoft/azure-maven-archetypes/pull/55 Adding the version property to default host.json
- [x] https://github.com/Microsoft/azure-maven-plugins/issues/364 Remove disabled flag from function.json
### Azure Web App plugin
- [x] #297 Provide user that ```<resources>``` block is missing as early as possible
- [x] #371 Update util functions to depend on properties instead of mojo
- [x] #353 Add configuration <schemaVersion> to specify that which version of schema to use
- [ ] 💪 #354 Refactoring ```<runtime>``` configuration
