### ISSUE TITLE
Maven Plugins Iteration Planning [9/24/2018 - 10/12/2018]

### ISSUE THREAD

**Issue by Flanker32** [Microsoft/azure-maven-plugins#396]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Azure Functions Plugin
- [ ] Divide the ci test into two parts, function plugin and webapp
- [ ] #244 Set up CI that runs E2E tests and verifies plugin updates for every release
- [ ] #394 Make debug port configurable 
- [ ] https://github.com/Microsoft/azure-maven-archetypes/issues/61 Change HttpTrigger authlevel to `Function`
- [ ] 💪 #261 Add more CI tests

### Azure Web App plugin

**Comment by jdneo** [comment]
@pragnagopa FYI
