### ISSUE TITLE
Maven Plugins Iteration Planning [10/15/2018 - 11/2/2018]

### ISSUE THREAD

**Issue by Flanker32** [Microsoft/azure-maven-plugins#421]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Azure Functions Plugin
- [x] #244 Set up E2E tests and verifies plugin updates for every release.
- [ ]  #261 Add more integration tests.
- [x]  #404 Update zipDeploy to use Run From Package
- [x] #412 Add support to specify Cardinality for EventHubTrigger
- [x] #420 Remove NotificationHubOutput
- [x] #417 Show error if building extensions.csproj fails

### Azure Web App Plugin
- [ ] #422 Add WildFly14 support for App Service Linux
- [x] Refactoring the configuration of Web App in V2 schema version
  - [x] #355 Refactoring the `deployment` configuration
  - [x] #354 Refactoring the `runtime` configuration
  - [x] Make the `region` property to be required
  - [x] #437 Make the `runtime` configuration optional if users config an existing web app
- [x] Update the default value of region to “West Europe"
