### ISSUE TITLE
Maven Plugins Iteration Planning [11/05/2018 - 11/23/2018] 

### ISSUE THREAD

**Issue by Flanker32** [Microsoft/azure-maven-plugins#467]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

#### Refactor function plugin
- [x] Refactor function binding, remove strong dependency on azure-functions-java-library functions #456
- [x] Redesign the process of function:add to provide default value #405
#### CI
- [x] Divide CI into maven plugin and maven archetype
- [ ] ⚫️ Add all the supported commands to CI #429
- [ ] 🏃 Add more integration tests #261
#### Bugs fix
- [x] can't trigger CosmosDB function  #466 

### Azure Web App Maven Plugin
- [ ] #468 Refactoring, decouple the Mojo with handlers
- [x] Documentation of V2 schema version
- [x] Integration tests for V2 schema version and bug fixing
- [x] Add new runtime WildFly support
