### ISSUE TITLE
Maven Plugins Iteration Planning [11/26/2018 - 12/14/2018] 

### ISSUE THREAD

**Issue by Flanker32** [Microsoft/azure-maven-plugins#513]
Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Azure Functions Plugin
- [x] Refactor the process of function:add #405
- [ ]  Add more integration tests #261

## Azure Web App
- [x] Upgrade AI SDK to 2.2.1 #514
