### ISSUE TITLE
[Enhancement] Enhance `azure-webapp:config`

### ISSUE THREAD

**Issue by Flanker32** [microsoft/azure-maven-plugins#854]
### Workflow
- [x]  `config` should give more choice on important properties  #855 
- [x] plugin could offer users to select existing resources  #856 
- [x] plugin could refactor the workflow of update configuration #857 
### Prompt
- [x] plugin could provide more user-friendly and valid names for properties #858 
- [x] plugin should provide more friendly names for properties options #859
